---
name: Manage Repo Labels

on:
  push:
    branches:
      - main
    paths:
      - .github/repo_labels.yml
      - .github/workflows/manage-repo-labels.yml
  workflow_dispatch:

jobs:
  manage-repo-labels:
    name: Manage Repo Labels
    # yamllint disable-line rule:line-length
    uses: worganisation/github-config-files/.github/workflows/__manage-repo-labels.yml@539b889c12470285760b747e8bb4a4c221213b59 # shared CI
    permissions:
      issues: write
