---
name: Prek Hooks

on:
  merge_group:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

concurrency:
  group: 'prek-hooks-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  prek:
    name: Prek Hooks
    # yamllint disable-line rule:line-length
    uses: worganisation/github-config-files/.github/workflows/__prek-hooks.yml@539b889c12470285760b747e8bb4a4c221213b59 # shared CI
    with:
      python-version: ''
      sync-project-dependencies: 'false'
    secrets: inherit
